[package]
authors = ["meng.fanjun <xmeng.fanjun@contract.isid.co.jp>"]
name = "rust-logme"
version = "0.1.0"

[dependencies]
chrono = "0.2"
lazy_static = "0.1"
pretty_env_logger = "*"
error-chain = "0.8.1"
futures = "0.1.9"
log = "0.3.6"
tokio-core = "0.1.4"
tokio-signal = "0.1.2"
