[package]
name = "rust-logme"
version = "0.1.0"
authors = ["meng.fanjun <xmeng.fanjun@contract.isid.co.jp>"]

[dependencies]
lazy_static = "0.1"
chrono = "0.2"
error-chain = "*"
pretty_env_logger = "*"
log = "*"
nix = "0.6"
signal = "0.3"
