[package]
name = "droplet"
version = "0.1.0"
authors = ["meng.fanjun <xmeng.fanjun@contract.isid.co.jp>"]

[dependencies]
bitflags = "=0.7.0"
byteorder = "=1.0.0"
chrono = "=0.2.25"
clap = "=2.20.0"
error-chain = "=0.8.1"
json = "=0.11.5"
lazy_static = "=0.2.2"
libc = "=0.2.18"
log = "=0.3.6"
ndarray = "=0.7.2"
num = "=0.1.36"
rand = "=0.3.15"
rayon = "=0.6.0"
regex = "=0.2.1"
reqwest = "=0.3.0"
serde = "=0.9.0-rc2"
tempdir = "=0.3.5"
toml = "=0.2.1"
url = "=1.3.0"

# Supplemental dependencies
env_logger = "=0.4.0"
serde_derive = "=0.9.0-rc2"
serde_json = "=0.9.0-rc1"
