[package]
name = "lazy"
version = "0.1.0"
authors = ["meng.fanjun <xmeng.fanjun@contract.isid.co.jp>"]

[dependencies]

[dependencies.lazy_static]
git = "https://github.com/rust-lang-nursery/lazy-static.rs"
