[package]
name = "sendgrid"
version = "0.1.0"
authors = ["meng.fanjun <xmeng.fanjun@contract.isid.co.jp>"]

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
reqwest = "*"
dotenv = "*"
error-chain = "*"
env_logger = "*"
log = "*"

