[package]
authors = ["meng.fanjun <xmeng.fanjun@contract.isid.co.jp>"]
name = "innolab_bot"
version = "0.1.0"

[dependencies]
dotenv = "0.8.0"
error-chain = "0.8.1"
log = "0.3.6"
opus = "0.2.0"
pretty_env_logger = "0.1.0"

[dependencies.tg_botapi]
optional = false
path = "rust-tg-botapi"
