[package]
authors = ["meng.fanjun <xmeng.fanjun@contract.isid.co.jp>"]
name = "firebase"
version = "0.1.0"

[dependencies]
dotenv = "0.8.0"
log = "0.3.6"
reqwest = "0.3.0"
serde = "0.9.3"
serde_derive = "0.9.2"
serde_json = "0.9.2"
