[package]
name = "jawbone"
version = "0.1.0"
authors = ["meng.fanjun <600913@gmail.com>"]

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
reqwest = "0.3"
dotenv = "0.8"
error-chain = "0.7"
pretty_env_logger = "0.1"
log = "0.3"

