[package]
name = "journal"
version = "0.1.0"
authors = ["meng.fanjun <xmeng.fanjun@contract.isid.co.jp>"]

[dependencies]
chrono = "0.2"
regex = "0.2"
lazy_static = "0.2"
pretty_env_logger = "*"
log = "*"
