[package]
authors = ["meng.fanjun <xmeng.fanjun@contract.isid.co.jp>"]
name = "journal"
version = "0.1.0"

[dependencies]
ansi_term = "0.9.0"
chrono = "0.2.25"
clap = "2.20.0"
lazy_static = "0.2"
log = "0.3.6"
pretty_env_logger = "0.1.0"
regex = "0.2"
